src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmployeRepository::class)]
class Employe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?int $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $poste = null;

    #[ORM\Column]
    private ?int $salaire = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dt_naissance = null;

    #[ORM\Column]
    private ?bool $isactive = null;

    #[ORM\OneToOne(targetEntity: self::class, cascade: ['persist', 'remove'])]
    private ?self $service = null;

    #[ORM\ManyToOne(inversedBy: 'employes')]
    private ?Service $employe = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPoste(): ?string
    {
        return $this->poste;
    }

    public function setPoste(string $poste): static
    {
        $this->poste = $poste;

        return $this;
    }

    public function getSalaire(): ?int
    {
        return $this->salaire;
    }

    public function setSalaire(int $salaire): static
    {
        $this->salaire = $salaire;

        return $this;
    }

    public function getDtNaissance(): ?\DateTimeInterface
    {
        return $this->dt_naissance;
    }

    public function setDtNaissance(\DateTimeInterface $dt_naissance): static
    {
        $this->dt_naissance = $dt_naissance;

        return $this;
    }

    public function isactive(): ?bool
    {
        return $this->isactive;
    }

    public function setIsactive(bool $isactive): static
    {
        $this->isactive = $isactive;

        return $this;
    }

    public function getService(): ?self
    {
        return $this->service;
    }

    public function setService(?self $service): static
    {
        $this->service = $service;

        return $this;
    }

    public function getEmploye(): ?Service
    {
        return $this->employe;
    }

    public function setEmploye(?Service $employe): static
    {
        $this->employe = $employe;

        return $this;
    }
}

src/Form/EmployeType.php
<?php

namespace App\Form;

use App\Entity\Employe;
use App\Entity\Service;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmployeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('prenom')
            ->add('nom')
            ->add('telephone')
            ->add('email')
            ->add('adresse')
            ->add('poste')
            ->add('salaire')
            ->add('dt_naissance', null, [
                'widget' => 'single_text',
            ])
            ->add('isactive')
            ->add('service', EntityType::class, [
                'class' => Employe::class,
                'choice_label' => 'id',
            ])
            ->add('employe', EntityType::class, [
                'class' => Service::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employe::class,
        ]);
    }
}

src/Controller/Back/EmployeController.php
<?php

namespace App\Controller\Back;

use App\Entity\Employe;
use App\Form\EmployeType;
use App\Repository\EmployeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/employe')]
final class EmployeController extends AbstractController
{
    #[Route(name: 'app_employe_index', methods: ['GET'])]
    public function index(EmployeRepository $employeRepository): Response
    {
        return $this->render('employe/index.html.twig', [
            'employes' => $employeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_employe_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $employe = new Employe();
        $form = $this->createForm(EmployeType::class, $employe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($employe);
            $entityManager->flush();

            return $this->redirectToRoute('app_employe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('employe/new.html.twig', [
            'employe' => $employe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_employe_show', methods: ['GET'])]
    public function show(Employe $employe): Response
    {
        return $this->render('employe/show.html.twig', [
            'employe' => $employe,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_employe_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Employe $employe, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EmployeType::class, $employe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_employe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('employe/edit.html.twig', [
            'employe' => $employe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_employe_delete', methods: ['POST'])]
    public function delete(Request $request, Employe $employe, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$employe->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($employe);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_employe_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/employe/_delete_form.html.twig
<form method="post" action="{{ path('app_employe_delete', {'id': employe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employe.id) }}">
    <button class="btn">Delete</button>
</form>

templates/employe/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/employe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Employe{% endblock %}

{% block body %}
    <h1>Edit Employe</h1>

    {{ include('employe/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_employe_index') }}">back to list</a>

    {{ include('employe/_delete_form.html.twig') }}
{% endblock %}

templates/employe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employe index{% endblock %}

{% block body %}
    <h1>Employe index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prenom</th>
                <th>Nom</th>
                <th>Telephone</th>
                <th>Email</th>
                <th>Adresse</th>
                <th>Poste</th>
                <th>Salaire</th>
                <th>Dt_naissance</th>
                <th>Isactive</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for employe in employes %}
            <tr>
                <td>{{ employe.id }}</td>
                <td>{{ employe.prenom }}</td>
                <td>{{ employe.nom }}</td>
                <td>{{ employe.telephone }}</td>
                <td>{{ employe.email }}</td>
                <td>{{ employe.adresse }}</td>
                <td>{{ employe.poste }}</td>
                <td>{{ employe.salaire }}</td>
                <td>{{ employe.dtNaissance ? employe.dtNaissance|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ employe.isactive ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_employe_show', {'id': employe.id}) }}">show</a>
                    <a href="{{ path('app_employe_edit', {'id': employe.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_employe_new') }}">Create new</a>
{% endblock %}

templates/employe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Employe{% endblock %}

{% block body %}
    <h1>Create new Employe</h1>

    {{ include('employe/_form.html.twig') }}

    <a href="{{ path('app_employe_index') }}">back to list</a>
{% endblock %}

templates/employe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employe{% endblock %}

{% block body %}
    <h1>Employe</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ employe.id }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ employe.prenom }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ employe.nom }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ employe.telephone }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ employe.email }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ employe.adresse }}</td>
            </tr>
            <tr>
                <th>Poste</th>
                <td>{{ employe.poste }}</td>
            </tr>
            <tr>
                <th>Salaire</th>
                <td>{{ employe.salaire }}</td>
            </tr>
            <tr>
                <th>Dt_naissance</th>
                <td>{{ employe.dtNaissance ? employe.dtNaissance|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Isactive</th>
                <td>{{ employe.isactive ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_employe_index') }}">back to list</a>

    <a href="{{ path('app_employe_edit', {'id': employe.id}) }}">edit</a>

    {{ include('employe/_delete_form.html.twig') }}
{% endblock %}